"""CLI constants."""

from __future__ import annotations

SKILLS_METADATA_PROTOCOL_VERSION: int = 4
CUSTOM_CHECK_PROTOCOL_VERSION: int = 1
COLOR_ALWAYS: str = "always"
COLOR_AUTO: str = "auto"
COLOR_NEVER: str = "never"
NO_COLOR_ENVIRONMENT_VARIABLE: str = "NO_COLOR"
CUSTOM_CHECK_TARGETS_ENVIRONMENT_VARIABLE: str = "FENSU_INTERNAL_CUSTOM_CHECK_TARGETS"
RUST_CUSTOM_HOST_PROTOCOL_VERSION: int = 1
RUST_CUSTOM_FACT_SCHEMA_VERSION: str = "rust-facts-v1"
RUST_CUSTOM_PARSER_CONTRACT_VERSION: str = "rust-syn-workspace-v1"
WEB_CUSTOM_HOST_PROTOCOL_VERSION: int = 1
REPOSITORY_CUSTOM_HOST_PROTOCOL_VERSION: int = 1
WEB_CUSTOM_FACT_SCHEMA_VERSION: str = "web-facts-v1"
TYPESCRIPT_CUSTOM_PARSER_CONTRACT_VERSION: str = "typescript-backend-v11"
SVELTE_CUSTOM_PARSER_CONTRACT_VERSION: str = "svelte-backend-v12"
