"""CLI constants."""

from __future__ import annotations

SKILLS_METADATA_PROTOCOL_VERSION: int = 4
CUSTOM_CHECK_PROTOCOL_VERSION: int = 1
COLOR_ALWAYS: str = "always"
COLOR_AUTO: str = "auto"
COLOR_NEVER: str = "never"
NO_COLOR_ENVIRONMENT_VARIABLE: str = "NO_COLOR"
CUSTOM_CHECK_TARGETS_ENVIRONMENT_VARIABLE: str = "FENSU_INTERNAL_CUSTOM_CHECK_TARGETS"
