"""Strata: an architecture linter for Python repos, with a public rule-authoring API."""

from __future__ import annotations

from strata.analysis.models import (
    AnnotationFacts,
    AttributeReferenceFact,
    CommentFact,
    DataclassFact,
    DiscardedProjectCallFact,
    FunctionConditionalFact,
    FunctionFacts,
    FunctionMetricFact,
    HygieneFacts,
    ImportAliasFact,
    ImportFact,
    MeaningfulReturnFact,
    MissingLocalAnnotationFact,
    MissingParameterAnnotationFact,
    MissingReturnAnnotationFact,
    MissingVariableAnnotationFact,
    ModuleDeclarationFacts,
    ModuleStatementFact,
    NamedCallFact,
    NodeId,
    OuterStateMutationFact,
    ParameterMutationFact,
    ParametrizeCaseFact,
    ParametrizeFact,
    ProjectCallFacts,
    ProjectDependency,
    ProjectFunctionFact,
    PytestFunctionFact,
    PytestModuleFacts,
    ReferenceFacts,
    SourceLocation,
    SourcePosition,
    SourceRange,
    SyntaxHandle,
    TypeDeclarationFact,
)
from strata.analysis.types import (
    FactAnalysis,
    ProjectAnalysis,
    RelationAnalysis,
    SyntaxAnalysis,
    TextAnalysis,
)
from strata.rules.authoring.main.define import rule
from strata.rules.authoring.models import Fault
from strata.rules.authoring.types import Family, RuleContext, Severity, Threshold

__all__ = [
    "AnnotationFacts",
    "AttributeReferenceFact",
    "CommentFact",
    "DataclassFact",
    "DiscardedProjectCallFact",
    "FactAnalysis",
    "Fault",
    "Family",
    "FunctionConditionalFact",
    "FunctionFacts",
    "FunctionMetricFact",
    "HygieneFacts",
    "ImportAliasFact",
    "ImportFact",
    "MeaningfulReturnFact",
    "MissingLocalAnnotationFact",
    "MissingParameterAnnotationFact",
    "MissingReturnAnnotationFact",
    "MissingVariableAnnotationFact",
    "ModuleDeclarationFacts",
    "ModuleStatementFact",
    "NamedCallFact",
    "NodeId",
    "OuterStateMutationFact",
    "ParameterMutationFact",
    "ParametrizeCaseFact",
    "ParametrizeFact",
    "ProjectAnalysis",
    "ProjectCallFacts",
    "ProjectDependency",
    "ProjectFunctionFact",
    "PytestFunctionFact",
    "PytestModuleFacts",
    "ReferenceFacts",
    "RelationAnalysis",
    "RuleContext",
    "Severity",
    "SourceLocation",
    "SourcePosition",
    "SourceRange",
    "SyntaxAnalysis",
    "SyntaxHandle",
    "TextAnalysis",
    "Threshold",
    "TypeDeclarationFact",
    "rule",
]
