"""Roles rule-family types."""

from __future__ import annotations

from enum import StrEnum


class RoleCode(StrEnum):
    """Stable roles rule codes."""

    MODELS_ONLY_MODELS = "FFR001"
    TYPES_ONLY_TYPES = "FFR002"
    CONSTANTS_ONLY_CONSTANTS = "FFR003"
    EXCEPTIONS_ONLY_EXCEPTIONS = "FFR004"
    MODEL_DECLARATION_OUTSIDE_MODELS = "FFR101"
    TYPE_DECLARATION_OUTSIDE_TYPES = "FFR102"
    CONSTANT_OUTSIDE_CONSTANTS = "FFR103"
    EXCEPTION_DECLARATION_OUTSIDE_EXCEPTIONS = "FFR104"
    BANNED_GENERIC_FILENAME = "FFR201"
    HELPERS_MODULE_NAME = "FFR202"
    CLASSES_MODULE_NAME = "FFR203"
    BANNED_GENERIC_PACKAGE_NAME = "FFR204"
    HELPERS_CLASSES_FILE_PRIVATE = "FFR205"
    HELPERS_PACKAGE_LAYOUT = "FFR301"
    MAIN_PACKAGE_LAYOUT = "FFR302"
    HELPERS_RESERVED_ROLE_FILENAMES = "FFR303"
    NESTED_DIRECT_MODULES = "FFR304"
    NESTED_DIRECT_SUBPACKAGES = "FFR305"
    TOP_LEVEL_DOMAIN_SHAPE = "FFR306"
    TOP_LEVEL_DIRECT_MODULES = "FFR307"
    SHARED_DOMAIN_PREFIX = "FFR308"
    LEAF_MAIN_BOUNDARY = "FFR309"
    ENTRY_MODULE_SHAPE = "FFR401"
    INIT_MODULE_EMPTY = "FFR402"
    NO_REEXPORT_SHIM = "FFR403"
    NO_INTERNAL_HELPER_EXPORTS = "FFR404"
    MAIN_ENTRY_NAME_COLLISION = "FFR405"
    PUBLIC_SURFACE_SHAPE = "FFR406"
    CLASSES_ONE_CLASS_PER_MODULE = "FFR501"
    HELPERS_PACKAGE_SHAPE = "FFR502"
    PRIVATE_DEFINITION_ORDERING = "FFR503"
    SOURCE_FILE_LINE_COUNT = "FFR601"
    TOOLING_ENTRYPOINT_SHAPE = "FFR701"
    TOOLING_ENTRYPOINT_DELEGATION = "FFR702"
    TOOLING_ENTRYPOINT_LINE_COUNT = "FFR703"
    RULES_ROLE_CONTENT = "FFR704"
    TOOLING_PACKAGE_LAYOUT = "FFR705"
    DESCRIPTIVE_RULE_MODULE_NAMES = "FFR706"
    CUSTOM_RULE_TEST_COVERAGE = "FFR707"


class RoleSymbol(StrEnum):
    """Python symbols with role-classification semantics."""

    TYPE_CHECKING_SYMBOL = "TYPE_CHECKING"
    NEW_TYPE = "NewType"
    TYPE_ALIAS = "TypeAlias"
    RULE = "rule"
