"""Operation names and the process-wide counter for performance tests."""

from fensu.instrumentation.classes.operation_counters import OperationCounters

OPERATION_COUNTERS: OperationCounters = OperationCounters()
PARSE_OPERATION: str = "parse_python_source"
NATIVE_PARSE_OPERATION: str = "parse_native_program"
DEPENDENCY_RECORD_OPERATION: str = "dependency_record"
RELATIVE_PATH_COMPUTE_OPERATION: str = "relative_path_compute"
CANONICAL_ENCODE_OPERATION: str = "canonical_encode"
FRESH_EVALUATION_OPERATION: str = "fresh_evaluation"
PYTHON_CORE_RULE_CALLBACK_OPERATION: str = "python_core_rule_callback"
EVALUATION_WORKER_PARTITION_OPERATION: str = "evaluation_worker_partition"
CACHE_RECORD_READ_OPERATION: str = "cache_record_read"
CACHE_RECORD_SCAN_OPERATION: str = "cache_record_scan"
CACHE_RECORD_WRITE_OPERATION: str = "cache_record_write"
CACHE_RECORD_DELETE_OPERATION: str = "cache_record_delete"
CACHE_MANIFEST_VALIDATION_OPERATION: str = "cache_manifest_validation"
CACHE_RECORD_BYTES_READ_OPERATION: str = "cache_record_bytes_read"
CACHE_RECORD_BYTES_WRITTEN_OPERATION: str = "cache_record_bytes_written"
PROJECT_QUERY_OBSERVATION_OPERATION: str = "project_query_observation"
PROJECT_QUERY_ANSWER_ITEM_OPERATION: str = "project_query_answer_item"
PROJECT_QUERY_CACHE_HIT_OPERATION: str = "project_query_cache_hit"
PROJECT_QUERY_CACHE_MISS_OPERATION: str = "project_query_cache_miss"
PROJECT_QUERY_SOURCE_OPERATION: str = "project_query_source"
PROJECT_QUERY_EXISTS_OPERATION: str = "project_query_exists"
PROJECT_QUERY_IS_FILE_OPERATION: str = "project_query_is_file"
PROJECT_QUERY_IS_DIR_OPERATION: str = "project_query_is_dir"
PROJECT_QUERY_DIRECTORY_ENTRIES_OPERATION: str = "project_query_directory_entries"
PROJECT_QUERY_GLOB_OPERATION: str = "project_query_glob"
PROJECT_QUERY_PYTHON_ANCHOR_OPERATION: str = "project_query_python_anchor"
PHASE_CONFIG_NANOSECONDS: str = "phase_config_nanoseconds"
PHASE_CATALOGUE_NANOSECONDS: str = "phase_catalogue_nanoseconds"
PHASE_DISCOVERY_NANOSECONDS: str = "phase_discovery_nanoseconds"
PHASE_GLOBAL_FINGERPRINT_NANOSECONDS: str = "phase_global_fingerprint_nanoseconds"
PHASE_CACHE_EVALUATION_NANOSECONDS: str = "phase_cache_evaluation_nanoseconds"
PHASE_FULL_EVALUATION_NANOSECONDS: str = "phase_full_evaluation_nanoseconds"
SNAPSHOT_ROOT_RELATIVIZE_OPERATION: str = "snapshot_root_relativize"
