"""Roles rule-family types."""

from __future__ import annotations

from enum import StrEnum


class RoleCode(StrEnum):
    """Stable roles rule codes."""

    MODELS_ONLY_MODELS = "SFR001"
    TYPES_ONLY_TYPES = "SFR002"
    CONSTANTS_ONLY_CONSTANTS = "SFR003"
    EXCEPTIONS_ONLY_EXCEPTIONS = "SFR004"
    MODEL_DECLARATION_OUTSIDE_MODELS = "SFR101"
    TYPE_DECLARATION_OUTSIDE_TYPES = "SFR102"
    CONSTANT_OUTSIDE_CONSTANTS = "SFR103"
    EXCEPTION_DECLARATION_OUTSIDE_EXCEPTIONS = "SFR104"
    BANNED_GENERIC_FILENAME = "SFR201"
    HELPERS_MODULE_NAME = "SFR202"
    CLASSES_MODULE_NAME = "SFR203"
    HELPERS_CLASSES_FILE_PRIVATE = "SFR205"
    HELPERS_PACKAGE_LAYOUT = "SFR301"
    MAIN_PACKAGE_LAYOUT = "SFR302"
    NESTED_DIRECT_MODULES = "SFR304"
    NESTED_DIRECT_SUBPACKAGES = "SFR305"
    TOP_LEVEL_ROLE_PLACEMENT = "SFR306"
    TOP_LEVEL_DIRECT_MODULES = "SFR307"
    ENTRY_MODULE_SHAPE = "SFR401"
    INIT_MODULE_EMPTY = "SFR402"
    NO_REEXPORT_SHIM = "SFR403"
    NO_INTERNAL_HELPER_EXPORTS = "SFR404"
    MAIN_ENTRY_NAME_COLLISION = "SFR405"
    CLASSES_ONE_CLASS_PER_MODULE = "SFR501"
    HELPERS_PACKAGE_SHAPE = "SFR502"
    PRIVATE_DEFINITION_ORDERING = "SFR503"
    SOURCE_FILE_LINE_COUNT = "SFR601"
