"""Roles rule-family types."""

from __future__ import annotations

from enum import StrEnum


class RoleCode(StrEnum):
    """Stable roles rule codes."""

    MODELS_ONLY_MODELS = "SFR001"
    TYPES_ONLY_TYPES = "SFR002"
    CONSTANTS_ONLY_CONSTANTS = "SFR003"
    EXCEPTIONS_ONLY_EXCEPTIONS = "SFR004"
    MODEL_DECLARATION_OUTSIDE_MODELS = "SFR101"
    TYPE_DECLARATION_OUTSIDE_TYPES = "SFR102"
    CONSTANT_OUTSIDE_CONSTANTS = "SFR103"
    EXCEPTION_DECLARATION_OUTSIDE_EXCEPTIONS = "SFR104"
    BANNED_GENERIC_FILENAME = "SFR201"
    HELPERS_MODULE_NAME = "SFR202"
    CLASSES_MODULE_NAME = "SFR203"
    BANNED_GENERIC_PACKAGE_NAME = "SFR204"
    HELPERS_CLASSES_FILE_PRIVATE = "SFR205"
    HELPERS_PACKAGE_LAYOUT = "SFR301"
    MAIN_PACKAGE_LAYOUT = "SFR302"
    NESTED_DIRECT_MODULES = "SFR304"
    NESTED_DIRECT_SUBPACKAGES = "SFR305"
    TOP_LEVEL_DOMAIN_SHAPE = "SFR306"
    TOP_LEVEL_DIRECT_MODULES = "SFR307"
    ENTRY_MODULE_SHAPE = "SFR401"
    INIT_MODULE_EMPTY = "SFR402"
    NO_REEXPORT_SHIM = "SFR403"
    NO_INTERNAL_HELPER_EXPORTS = "SFR404"
    MAIN_ENTRY_NAME_COLLISION = "SFR405"
    PUBLIC_SURFACE_SHAPE = "SFR406"
    CLASSES_ONE_CLASS_PER_MODULE = "SFR501"
    HELPERS_PACKAGE_SHAPE = "SFR502"
    PRIVATE_DEFINITION_ORDERING = "SFR503"
    SOURCE_FILE_LINE_COUNT = "SFR601"
    TOOLING_ENTRYPOINT_SHAPE = "SFR701"
    TOOLING_ENTRYPOINT_DELEGATION = "SFR702"
    TOOLING_ENTRYPOINT_LINE_COUNT = "SFR703"
    RULES_ROLE_CONTENT = "SFR704"
    TOOLING_PACKAGE_LAYOUT = "SFR705"
    DESCRIPTIVE_RULE_MODULE_NAMES = "SFR706"
    CUSTOM_RULE_TEST_COVERAGE = "SFR707"


class RoleSymbol(StrEnum):
    """Python symbols with role-classification semantics."""

    TYPE_CHECKING_SYMBOL = "TYPE_CHECKING"
    NEW_TYPE = "NewType"
    TYPE_ALIAS = "TypeAlias"
    RULE = "rule"
