"""Type stubs for the native fact-extraction extension."""

from pathlib import Path
from typing import Any

class ProgramHandle: ...

def annotation_facts(handle: ProgramHandle, path: Path) -> Any: ...
def backend_version() -> str: ...
def comment_facts(handle: ProgramHandle, path: Path) -> tuple[Any, ...]: ...
def outer_state_mutation_facts(handle: ProgramHandle, path: Path) -> tuple[Any, ...]: ...
def reference_facts(handle: ProgramHandle, path: Path) -> Any: ...
def evaluate_rule_call_facts(handle: ProgramHandle, path: Path) -> tuple[Any, ...]: ...
def test_function_facts(handle: ProgramHandle, path: Path) -> tuple[Any, ...]: ...
def test_module_facts(handle: ProgramHandle, path: Path) -> Any: ...
def hygiene_facts(handle: ProgramHandle, path: Path) -> Any: ...
def control_flow_facts(handle: ProgramHandle, path: Path) -> tuple[Any, Any, Any]: ...
def dataclass_facts(handle: ProgramHandle, path: Path) -> tuple[Any, ...]: ...
def project_facts(handle: ProgramHandle, path: Path) -> tuple[Any, Any]: ...
def parse_program(source: str, major: int, minor: int) -> ProgramHandle: ...
def check_syntax(source: str, major: int, minor: int) -> tuple[int, int, str] | None: ...
def list_syntax_nodes(
    source: str, major: int, minor: int
) -> list[tuple[str, tuple[int, int, int, int] | None]]: ...
def module_declaration_facts(handle: ProgramHandle, path: Path) -> Any: ...
def function_contract_facts(handle: ProgramHandle, path: Path) -> Any | None: ...
def function_facts(handle: ProgramHandle, path: Path) -> Any: ...
def parameter_mutation_facts(handle: ProgramHandle, path: Path) -> tuple[Any, ...]: ...
def locate_byte_offset(source: str, offset: int) -> tuple[int, int]: ...
