"""Type stubs for the native fact-extraction extension."""

def backend_version() -> str: ...
def check_syntax(source: str, major: int, minor: int) -> tuple[int, int, str] | None: ...
def locate_byte_offset(source: str, offset: int) -> tuple[int, int]: ...
