"""Public attribute ownership declarations."""

PUBLIC_ATTRIBUTES: dict[str, tuple[str, str]] = {
    "AnnotationFacts": ("strata.analysis.models", "AnnotationFacts"),
    "AttributeReferenceFact": ("strata.analysis.models", "AttributeReferenceFact"),
    "CommentFact": ("strata.analysis.models", "CommentFact"),
    "DataclassFact": ("strata.analysis.models", "DataclassFact"),
    "DiscardedProjectCallFact": ("strata.analysis.models", "DiscardedProjectCallFact"),
    "EvaluateRuleCallFact": ("strata.analysis.models", "EvaluateRuleCallFact"),
    "FactAnalysis": ("strata.analysis.types", "FactAnalysis"),
    "Fault": ("strata.rules.authoring.models", "Fault"),
    "Family": ("strata.rules.authoring.types", "Family"),
    "FunctionConditionalFact": ("strata.analysis.models", "FunctionConditionalFact"),
    "FunctionFacts": ("strata.analysis.models", "FunctionFacts"),
    "FunctionMetricFact": ("strata.analysis.models", "FunctionMetricFact"),
    "HygieneFacts": ("strata.analysis.models", "HygieneFacts"),
    "ImportAliasFact": ("strata.analysis.models", "ImportAliasFact"),
    "ImportFact": ("strata.analysis.models", "ImportFact"),
    "MeaningfulReturnFact": ("strata.analysis.models", "MeaningfulReturnFact"),
    "MissingLocalAnnotationFact": ("strata.analysis.models", "MissingLocalAnnotationFact"),
    "MissingParameterAnnotationFact": (
        "strata.analysis.models",
        "MissingParameterAnnotationFact",
    ),
    "MissingReturnAnnotationFact": ("strata.analysis.models", "MissingReturnAnnotationFact"),
    "MissingVariableAnnotationFact": ("strata.analysis.models", "MissingVariableAnnotationFact"),
    "ModuleDeclarationFacts": ("strata.analysis.models", "ModuleDeclarationFacts"),
    "ModuleStatementFact": ("strata.analysis.models", "ModuleStatementFact"),
    "NamedCallFact": ("strata.analysis.models", "NamedCallFact"),
    "NodeId": ("strata.analysis.models", "NodeId"),
    "OuterStateMutationFact": ("strata.analysis.models", "OuterStateMutationFact"),
    "ParameterMutationFact": ("strata.analysis.models", "ParameterMutationFact"),
    "ParametrizeCaseFact": ("strata.analysis.models", "ParametrizeCaseFact"),
    "ParametrizeDimensionFact": ("strata.analysis.models", "ParametrizeDimensionFact"),
    "ParametrizeFact": ("strata.analysis.models", "ParametrizeFact"),
    "ProjectAnalysis": ("strata.analysis.types", "ProjectAnalysis"),
    "ProjectCallFacts": ("strata.analysis.models", "ProjectCallFacts"),
    "ProjectDependency": ("strata.analysis.models", "ProjectDependency"),
    "ProjectFunctionFact": ("strata.analysis.models", "ProjectFunctionFact"),
    "PytestFunctionFact": ("strata.analysis.models", "PytestFunctionFact"),
    "PytestModuleFacts": ("strata.analysis.models", "PytestModuleFacts"),
    "ReferenceFacts": ("strata.analysis.models", "ReferenceFacts"),
    "RelationAnalysis": ("strata.analysis.types", "RelationAnalysis"),
    "RuleCase": ("strata.rules.testing.models", "RuleCase"),
    "RuleCaseForm": ("strata.analysis.types", "RuleCaseForm"),
    "RuleContext": ("strata.rules.authoring.types", "RuleContext"),
    "RuleFile": ("strata.rules.testing.models", "RuleFile"),
    "RuleResult": ("strata.rules.testing.models", "RuleResult"),
    "RuleTestAssociationFact": ("strata.analysis.models", "RuleTestAssociationFact"),
    "Severity": ("strata.rules.authoring.types", "Severity"),
    "SourceLocation": ("strata.analysis.models", "SourceLocation"),
    "SourcePosition": ("strata.analysis.models", "SourcePosition"),
    "SourceRange": ("strata.analysis.models", "SourceRange"),
    "StaticReferenceFact": ("strata.analysis.models", "StaticReferenceFact"),
    "SyntaxAnalysis": ("strata.analysis.types", "SyntaxAnalysis"),
    "SyntaxHandle": ("strata.analysis.models", "SyntaxHandle"),
    "TextAnalysis": ("strata.analysis.types", "TextAnalysis"),
    "Threshold": ("strata.rules.authoring.types", "Threshold"),
    "TypeDeclarationFact": ("strata.analysis.models", "TypeDeclarationFact"),
    "evaluate_rule": ("strata.rules.testing.main.evaluate_rule", "evaluate_rule"),
    "rule": ("strata.rules.authoring.main.define", "rule"),
}
