"""First-class Rust rule-pack metadata backed by the structure engine."""

from __future__ import annotations

from fensu.config.constants import RUST_RULE_PACK
from fensu.config.types import AnalyzerId
from fensu.rules.authoring.models import RuleOption, RuleSpec
from fensu.rules.authoring.types import ExecutionOwner, Family, RuleKind

_IMPLEMENTATION_CODES: tuple[str, ...] = (
    "RSA103",
    "RSH001",
    "RSH002",
    "RSH003",
    "RSH004",
    "RSH005",
    "RSH006",
    "RSH007",
    "RSH008",
    "RSH010",
    "RSH011",
    "RSH012",
    "RSH013",
    "RSH901",
    "RSH902",
    "RSL001",
    "RSL002",
    "RSL101",
    "RSL102",
    "RSL103",
    "RSL104",
    "RSL105",
    "RSL110",
    "RSL301",
    "RSL302",
    "RSL303",
    "RSL304",
    "RSL305",
    "RSL306",
    "RSL307",
    "RSL901",
    "RSN001",
    "RSN002",
    "RSN003",
    "RSN004",
    "RSR001",
    "RSR002",
    "RSR003",
    "RSR004",
    "RSR101",
    "RSR102",
    "RSR103",
    "RSR104",
    "RSR201",
    "RSR202",
    "RSR204",
    "RSR205",
    "RSR301",
    "RSR302",
    "RSR303",
    "RSR304",
    "RSR305",
    "RSR306",
    "RSR307",
    "RSR308",
    "RSR309",
    "RSR310",
    "RSR401",
    "RSR402",
    "RSR403",
    "RSR404",
    "RSR405",
    "RSR406",
    "RSR502",
    "RSR503",
    "RSR601",
    "RSR701",
    "RSR702",
    "RSR703",
    "RSR704",
    "RSR705",
    "RSR706",
    "RSS001",
    "RSS002",
    "RSS003",
    "RSS010",
    "RSS011",
    "RSS101",
    "RSS102",
    "RSS110",
    "RSS120",
    "RSS130",
    "RSS131",
    "RSS201",
    "RST001",
    "RST002",
    "RST003",
    "RST004",
    "RST005",
    "RST006",
    "RST007",
    "RST008",
    "RST101",
    "RST102",
    "RST103",
    "RST104",
    "RST105",
    "RST110",
    "RST201",
    "RST202",
    "RST203",
    "RST204",
    "RST301",
    "RST302",
    "RST401",
    "RST402",
    "RST403",
    "RST404",
    "RST405",
    "RST406",
    "RST407",
    "RST408",
    "RST411",
    "RST412",
    "RST413",
    "RST414",
    "RST420",
)

_FAMILIES: dict[str, Family] = {
    "A": Family.ANNOTATIONS,
    "H": Family.HYGIENE,
    "L": Family.LAYERS,
    "N": Family.NAMING,
    "R": Family.ROLES,
    "S": Family.SHAPE,
    "T": Family.TESTS,
}

_OPTIONS: dict[str, tuple[RuleOption[object], ...]] = {
    "RSR601": (RuleOption.integer(name="max_file_lines", default=2000, minimum=1),),
    "RSS010": (RuleOption.integer(name="max_arguments", default=10, minimum=1),),
    "RSS011": (RuleOption.integer(name="max_statements", default=70, minimum=1),),
    "RSS001": (RuleOption.integer(name="max_statements", default=40, minimum=1),),
    "RSS002": (RuleOption.integer(name="max_distinct_calls", default=20, minimum=1),),
    "RSS003": (RuleOption.integer(name="max_locals", default=20, minimum=1),),
    "RSR301": (RuleOption.integer(name="max_modules", default=10, minimum=1),),
    "RSR302": (RuleOption.integer(name="max_modules", default=20, minimum=1),),
    "RSL301": (RuleOption.string_list(name="forbidden_packages", default=()),),
    "RSL102": (
        RuleOption.string_list(name="packages", default=()),
        RuleOption.string_list(name="restricted_paths", default=("rules",)),
        RuleOption.string(
            name="remediation", default="consume shared fact models instead of parser or AST types"
        ),
    ),
    "RSL304": (RuleOption.string_list(name="crate_names", default=()),),
    "RSL305": (
        RuleOption.string_list(name="domain_paths", default=()),
        RuleOption.string_list(name="role_paths", default=()),
        RuleOption.string_list(name="intentional_layout_paths", default=()),
    ),
}


def rust_rules() -> tuple[RuleSpec, ...]:
    """Return Rust pack identities for every structure-engine implementation."""

    return tuple(
        RuleSpec(
            code=f"FP{implementation}",
            family=_FAMILIES[implementation[2]],
            slug=f"rust-{implementation.lower()}",
            message="Rust workspace structure policy violation.",
            remediation="Run fensu check for the diagnostic's rule-specific remediation.",
            analyzers=(AnalyzerId.RUST,),
            execution_owner=ExecutionOwner.PROJECT,
            kind=RuleKind.PACK,
            pack=RUST_RULE_PACK,
            implementation_code=implementation,
            options=_OPTIONS.get(implementation, ()),
        )
        for implementation in _IMPLEMENTATION_CODES
    )
