"""Public attribute ownership declarations."""

PUBLIC_ATTRIBUTES: dict[str, tuple[str, str]] = {
    "ArchitectureGraph": ("fensu.rules.authoring.models", "ArchitectureGraph"),
    "AnalyzerId": ("fensu.config.types", "AnalyzerId"),
    "AnnotationFacts": ("fensu.analysis.models", "AnnotationFacts"),
    "AssignmentReferenceFact": ("fensu.analysis.models", "AssignmentReferenceFact"),
    "AttributeReferenceFact": ("fensu.analysis.models", "AttributeReferenceFact"),
    "AuthoredImport": ("fensu.rules.authoring.models", "AuthoredImport"),
    "ClassDeclarationFact": ("fensu.analysis.models", "ClassDeclarationFact"),
    "ClassMethodFact": ("fensu.analysis.models", "ClassMethodFact"),
    "CommentFact": ("fensu.analysis.models", "CommentFact"),
    "ComparisonFact": ("fensu.analysis.models", "ComparisonFact"),
    "ContractBehavior": ("fensu.config.types", "ContractBehavior"),
    "DataclassFact": ("fensu.analysis.models", "DataclassFact"),
    "DefinitionIdentity": ("fensu.analysis.models", "DefinitionIdentity"),
    "DiscardedProjectCallFact": ("fensu.analysis.models", "DiscardedProjectCallFact"),
    "EvaluateRuleCallFact": ("fensu.analysis.models", "EvaluateRuleCallFact"),
    "ExecutionOwner": ("fensu.rules.authoring.types", "ExecutionOwner"),
    "FactAnalysis": ("fensu.analysis.types", "FactAnalysis"),
    "File": ("fensu.rules.authoring.models", "File"),
    "FilePosition": ("fensu.rules.authoring.models", "FilePosition"),
    "Fault": ("fensu.rules.authoring.models", "Fault"),
    "Family": ("fensu.rules.authoring.types", "Family"),
    "FunctionConditionalFact": ("fensu.analysis.models", "FunctionConditionalFact"),
    "FunctionFacts": ("fensu.analysis.models", "FunctionFacts"),
    "FunctionMetricFact": ("fensu.analysis.models", "FunctionMetricFact"),
    "HygieneFacts": ("fensu.analysis.models", "HygieneFacts"),
    "ImportAliasFact": ("fensu.analysis.models", "ImportAliasFact"),
    "ImportFact": ("fensu.analysis.models", "ImportFact"),
    "ImportCycle": ("fensu.rules.authoring.models", "ImportCycle"),
    "ImportEdge": ("fensu.rules.authoring.models", "ImportEdge"),
    "ImportResolution": ("fensu.rules.authoring.types", "ImportResolution"),
    "LiteralArgumentFact": ("fensu.analysis.models", "LiteralArgumentFact"),
    "LocalCallEdgeFact": ("fensu.analysis.models", "LocalCallEdgeFact"),
    "MeaningfulReturnFact": ("fensu.analysis.models", "MeaningfulReturnFact"),
    "MissingLocalAnnotationFact": ("fensu.analysis.models", "MissingLocalAnnotationFact"),
    "MissingParameterAnnotationFact": (
        "fensu.analysis.models",
        "MissingParameterAnnotationFact",
    ),
    "MissingReturnAnnotationFact": ("fensu.analysis.models", "MissingReturnAnnotationFact"),
    "MissingVariableAnnotationFact": ("fensu.analysis.models", "MissingVariableAnnotationFact"),
    "ModuleDeclarationFacts": ("fensu.analysis.models", "ModuleDeclarationFacts"),
    "ModuleStatementFact": ("fensu.analysis.models", "ModuleStatementFact"),
    "ModuleNode": ("fensu.rules.authoring.models", "ModuleNode"),
    "ModuleVisibility": ("fensu.rules.authoring.types", "ModuleVisibility"),
    "NamedCallFact": ("fensu.analysis.models", "NamedCallFact"),
    "NodeId": ("fensu.analysis.models", "NodeId"),
    "OuterStateMutationFact": ("fensu.analysis.models", "OuterStateMutationFact"),
    "ParameterMutationFact": ("fensu.analysis.models", "ParameterMutationFact"),
    "ParameterMutationOccurrenceFact": (
        "fensu.analysis.models",
        "ParameterMutationOccurrenceFact",
    ),
    "ParametrizeCaseFact": ("fensu.analysis.models", "ParametrizeCaseFact"),
    "ParametrizeDimensionFact": ("fensu.analysis.models", "ParametrizeDimensionFact"),
    "ParametrizeFact": ("fensu.analysis.models", "ParametrizeFact"),
    "ProjectAnalysis": ("fensu.analysis.types", "ProjectAnalysis"),
    "Project": ("fensu.rules.authoring.models", "Project"),
    "ProjectPath": ("fensu.rules.authoring.models", "ProjectPath"),
    "ProjectTree": ("fensu.rules.authoring.models", "ProjectTree"),
    "ProjectCallFacts": ("fensu.analysis.models", "ProjectCallFacts"),
    "ProjectDependency": ("fensu.analysis.models", "ProjectDependency"),
    "ProjectFunctionFact": ("fensu.analysis.models", "ProjectFunctionFact"),
    "PytestFunctionFact": ("fensu.analysis.models", "PytestFunctionFact"),
    "PytestModuleFacts": ("fensu.analysis.models", "PytestModuleFacts"),
    "QualifiedReferenceFact": ("fensu.analysis.models", "QualifiedReferenceFact"),
    "ReferenceFacts": ("fensu.analysis.models", "ReferenceFacts"),
    "ReturnAnnotationCategory": ("fensu.analysis.types", "ReturnAnnotationCategory"),
    "RelationAnalysis": ("fensu.analysis.types", "RelationAnalysis"),
    "RuleCase": ("fensu.rules.testing.models", "RuleCase"),
    "RuleCaseForm": ("fensu.analysis.types", "RuleCaseForm"),
    "RuleContext": ("fensu.rules.authoring.types", "RuleContext"),
    "RuleFile": ("fensu.rules.testing.models", "RuleFile"),
    "RuleOption": ("fensu.rules.authoring.models", "RuleOption"),
    "RuleResult": ("fensu.rules.testing.models", "RuleResult"),
    "RustCrateFact": ("fensu.rules.authoring.models", "RustCrateFact"),
    "RustDependencyFact": ("fensu.rules.authoring.models", "RustDependencyFact"),
    "RustFileFacts": ("fensu.rules.authoring.models", "RustFileFacts"),
    "RustItemFact": ("fensu.rules.authoring.models", "RustItemFact"),
    "RustItemKind": ("fensu.rules.authoring.types", "RustItemKind"),
    "RustTargetFact": ("fensu.rules.authoring.models", "RustTargetFact"),
    "RustUseFact": ("fensu.rules.authoring.models", "RustUseFact"),
    "RustUseResolution": ("fensu.rules.authoring.types", "RustUseResolution"),
    "RustVisibility": ("fensu.rules.authoring.types", "RustVisibility"),
    "RustWorkspaceFacts": ("fensu.rules.authoring.models", "RustWorkspaceFacts"),
    "RuleTestAssociationFact": ("fensu.analysis.models", "RuleTestAssociationFact"),
    "ScopeName": ("fensu.discovery.types", "ScopeName"),
    "Severity": ("fensu.rules.authoring.types", "Severity"),
    "SourceLocation": ("fensu.analysis.models", "SourceLocation"),
    "SourcePosition": ("fensu.analysis.models", "SourcePosition"),
    "SourceRange": ("fensu.analysis.models", "SourceRange"),
    "SourceKind": ("fensu.rules.authoring.types", "SourceKind"),
    "StaticReferenceFact": ("fensu.analysis.models", "StaticReferenceFact"),
    "SyntaxAnalysis": ("fensu.analysis.types", "SyntaxAnalysis"),
    "SyntaxHandle": ("fensu.analysis.models", "SyntaxHandle"),
    "TextAnalysis": ("fensu.analysis.types", "TextAnalysis"),
    "Threshold": ("fensu.rules.authoring.types", "Threshold"),
    "TypeDeclarationFact": ("fensu.analysis.models", "TypeDeclarationFact"),
    "evaluate_rule": ("fensu.rules.testing.main.evaluate_rule", "evaluate_rule"),
    "rule": ("fensu.rules.authoring.main.define", "rule"),
}
